### ISSUE TITLE
Intermittent program crash on multiple fits

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyDiffractionApp#35]
BUG

**Comment by rozyczko** [comment]
I have run multiple continuous fits with all engines, never getting a crash.

**Comment by AndrewSazonov** [comment]
This bug seems not reproducible or, let's say, half reproducible on MacOS 10.13.6 (`easyAppGui`: `develop` branch, `easyDiffractionApp`: `fit_stop` branch). I launch `easyDiffraction` via `Poetry`/`PyCharm`, load the PbSO4 project, go to the analysis page, select 1 parameter to refine (lattice constant a) and click the start fitting button. Approximately 50% of the time the fitting is finished properly, but in the other 50% of the time the application crashes with a message: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV).`

**Comment by rozyczko** [comment]
Windows 10, `easyAppGui` and `easyDiffractionApp` branches the same as yours, launching from both `poetry run easyDiffraction` and from within `visual studio code`, load `PbSO4` and performed the same set of fits.
None of them failed. Changed parameters, switched to another Windows machine with the same result.

Reminds me the issue of the intermittent windows but which would not show up on my dev machines :)

I'll try next on a clean Windows VM, installing the pre-release package

**Comment by rozyczko** [comment]
Same on a clean Windows VM - no crashes with the most recent `row_scroll` branch installer

**Comment by rozyczko** [comment]
Tested on bare metal mac mini (192.168.1.40) on installed version from the `develop` branch.
As noticed by @AndrewSazonov , the app fails every other/third time fitting is run.
This means it is a mac os specific issue.
First thing to check if threading. I'll create a build based on the `develop` source but without threading and test it on the VM

**Comment by rozyczko** [comment]
The problem does seem to originate with threading after all. The non-threaded version of `develop` works just fine on the test mac.

**Comment by rozyczko** [comment]
Most recent commit in `fit_stop` seems to have fixed the issue.
Please test the installer from that branch.
